type BasicTypes = 'boolean' | 'integer' | 'number' | 'string'

type CompoundTypes = 'array' | 'map' | 'record' | 'set'

type SpecialTypes = 'foreign'

// generic properties of all type definitions
interface GenericProperties<T extends BasicTypes | CompoundTypes | SpecialTypes> {
  type: T
  // whether it must be set
  required?: boolean
  // default value arrording to the field type
  default?: unknown
  // the field will be automatically generated by server if auto is set to true
  auto?: true
  // uniqueness should be checked by server
  unique?: boolean
}

interface NumberValidators {
  between?: [min: number, max: number]
  gt?: number
}

interface StringValidators {
  len_eq?: number
  len_max?: number
  len_min?: number
  match_none?: { err: string; pattern: string }[]
}

// field validator properties
interface GenericValidators {
  eq?: unknown
  ne?: unknown
  match?: unknown
  not_match?: unknown
  match_all?: unknown
  match_any?: unknown
  starts_with?: unknown
  one_of?: unknown
  contains?: unknown
  is_regex?: unknown
  custom_validator?: unknown
}

export interface BooleanType extends GenericProperties<'boolean'> {}

export interface IntegerType extends GenericProperties<'integer'>, NumberValidators {}

export interface NumberType extends GenericProperties<'number'>, NumberValidators {}

export interface StringType extends GenericProperties<'string'>, GenericValidators, StringValidators {}

export interface ArrayType extends GenericProperties<'array'> {
  elements: StringType
  contains?: string[]
}

interface MapType extends GenericProperties<'map'> {
  keys: unknown[]
  values: unknown[]
}

interface RecordType extends GenericProperties<'record'> {
  fields: FieldType[]
}

interface SetType extends GenericProperties<'set'> {
  elements: unknown[]
}

interface ForeignType extends GenericProperties<'foreign'> {
  // eq can only be null when type is 'foreign'
  eq: null
  // type of the entity referenced by this entity
  reference: string
}

export type FieldType = BooleanType | IntegerType | NumberType | StringType | ArrayType | MapType | RecordType | SetType

export interface FieldSchema {
  [key: string]: FieldType
}
